[phases.setup]
nixpkgs = ["openssl", "nodejs", "python3", "gcc", "make", "libjpeg", "cairo", "pango", "pixman"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production" 