[phases.setup]
nixpkgs = ["openssl", "nodejs", "python3", "gcc", "make", "libjpeg", "cairo", "pango", "pixman", "pkg-config"]
aptPkgs = ["libssl-dev"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps",
  "npm rebuild canvas --update-binary || true"
]

[phases.build]
cmds = [
  "node scripts/deploy-setup.js",
  "npm run build"
]

[phases.setup.env]
LD_LIBRARY_PATH = "/usr/lib"
PKG_CONFIG_PATH = "/usr/lib/pkgconfig"

[start]
cmd = "npm start"
onFailure = "restart"
restartLimit = 5

[variables]
NODE_ENV = "production"

# This allows cross-platform symlinks
[phases.setup.cmds]
opensslSymlinks = "mkdir -p /usr/local/lib && ln -sf /usr/lib/libssl.so /usr/local/lib/libssl.so.1.1 || true && ln -sf /usr/lib/libcrypto.so /usr/local/lib/libcrypto.so.1.1 || true" 