[phases.setup]
nixPkgs = ["nodejs", "openssl"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=2048"
PRISMA_CLIENT_ENGINE_TYPE = "binary"

# This allows cross-platform symlinks
[phases.setup.cmds]
opensslSymlinks = "mkdir -p /usr/local/lib && ln -sf /usr/lib/libssl.so /usr/local/lib/libssl.so.1.1 || true && ln -sf /usr/lib/libcrypto.so /usr/local/lib/libcrypto.so.1.1 || true" 