[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
watchPatterns = ["prisma/**", "src/**", "app/**", "components/**", "public/**", "styles/**", "lib/**"]

[deploy]
startCommand = "node scripts/railway-entrypoint.js"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[variables]
NIXPACKS_PKGS = "openssl"
NODE_OPTIONS = "--max-old-space-size=2048"

[phases.build]
nixPackages = ["openssl", "nodejs", "python3", "gcc", "git", "make", "cairo", "pango", "pixman", "libjpeg", "pkgconfig"] 