[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

[variables]
NIXPACKS_PKGS = "openssl openssl-1.1.1 openssl-1.1.1-dev" 