[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npm run build"
watchPatterns = ["prisma/**", "src/**", "app/**", "components/**", "public/**", "styles/**", "lib/**"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["openssl", "nodejs", "python3", "gcc", "git", "make", "cairo", "pango", "pixman", "libjpeg", "pkgconfig"]
aptPkgs = ["libssl-dev"]

[phases.build]
cmd = "npm run build"
env = ["NODE_ENV=production", "PRISMA_CLIENT_ENGINE_TYPE=binary"]

[variables]
NIXPACKS_PKGS = "openssl"
NODE_OPTIONS = "--max-old-space-size=2048"
PRISMA_CLIENT_ENGINE_TYPE = "binary"

[build.env]
NIXPACKS_NODE_VERSION = "18"

[nixpacks]
install-cmd = "apk add --no-cache openssl" 