[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npx prisma generate && npm run build"
watchPatterns = ["prisma/**", "src/**", "app/**", "components/**", "public/**", "styles/**", "lib/**"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[phases.setup]
nixPkgs = ["nodejs", "openssl"]

[phases.build]
cmds = [
  "npm install --legacy-peer-deps",
  "npx prisma generate",
  "npm run build"
]

[phases.setup.env]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=2048"
PRISMA_CLIENT_ENGINE_TYPE = "binary"

[build.env]
NIXPACKS_NODE_VERSION = "18"

[nixpacks]
install-cmd = "apk add --no-cache openssl" 